import { name as packageName } from '../../package.json';

export const PACKAGE_NAME = packageName;

export const WORKING_DIR = process.cwd();

export const ENV_MODULE_COMMENT = `// THIS FILE WAS AUTOGENERATED BY ${PACKAGE_NAME} -- DO NOT MODIFY`;
