import { name as packageName } from '../../package.json';

export const PACKAGE_NAME = packageName;

export const ENV_FILENAME = '.env';

export const ENV_MODULE_COMMENT = `// THIS FILE WAS AUTOGENERATED BY ${PACKAGE_NAME} -- DO NOT MODIFY\n`;

export const COMMANDS = ['setup', 'watch'] as const;

export const GIT_FILTER_NAME = 'dotenv-hot-env-module';

const GIT_FILTER_SCRIPT_FILENAME = `git-filter-${GIT_FILTER_NAME}.sh`;
export const GIT_FILTER_SCRIPT_DIR = 'scripts';
export const GIT_FILTER_SCRIPT_FULLPATH = `${GIT_FILTER_SCRIPT_DIR}/${GIT_FILTER_SCRIPT_FILENAME}`;

export const GIT_FILTER_SCRIPT_CONTENTS = `echo "${ENV_MODULE_COMMENT}"`;

export const GITATTRIBUTES_FILE = '.gitattributes';
