import fs from 'fs';
import { ENV_MODULE_COMMENT } from './constants';

/* Can't already have a env.js or env.ts file, unless it was generated by this tool. */
export const checkForExistingEnvModule = (
  envModulePath: string,
): string | undefined => {
  const hasEnvModuleAlready = fs.existsSync(envModulePath);

  if (hasEnvModuleAlready) {
    const contents = fs.readFileSync(envModulePath, 'utf-8');
    if (!contents.includes(ENV_MODULE_COMMENT)) {
      return `You already have a file at ${envModulePath}, and that file would be overwritten by this tool. Please remove it.`;
    }
  }
  return undefined;
};

export const writeEnvModuleInit = (envFile: string): void => {
  fs.writeFileSync(envFile, ENV_MODULE_COMMENT);
};
